version: "3"

services:
    web:
        # image: node
        # volumes:
        #     - ./:/usr/src/
       build: .
        depends_on:
            - mongo
        ports:
            - "3000:3000"
        # working_dir: /usr/src
        command: npm start
    mongo:
        image: mongo
        ports:
            - "27017:27017"
